spring:
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/outboxtable_db?allowPublicKeyRetrieval=true&autoReconnect=true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/testObjectSchema?allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: mdymen_pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8090
